se_model:
  input_dims: 128
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 5000
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 200

spec_model:
  input_dims: 128
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.0001
  epochs: 1600
  save_epoch: 200
  eval_epoch: 100
  lambda: 10
  lr: 0.00005
  batch_size: 1000
  lambda: 100

dataset:
  name: "CIFAR10"
  path: "/root/dataset/CIFAR10-MCR2"
  num: 10000
  num_cluster: 10

params: 
  device: 'cuda'
  se_pretrained: True
  se_model_path: 'se_model/CIFAR10/senet/se_CIFAR10_4999.pt'