se_model:
  input_dims: 128
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 5000
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 400
  gamma: 200
  lmbd: 0.9

spec_model:
  input_dims: 128
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.001
  epochs: 2000
  save_epoch: 500
  eval_epoch: 100
  lr: 0.00001
  batch_size: 400
  lambda: 10
  alpha: 1

dataset:
  name: "CIFAR100"
  path: "/root/dataset/CIFAR100-MCR2"
  num: 10000
  num_cluster: 100

params: 
  device: 'cuda'
  se_pretrained: True
  se_model_path: 'se_model/CIFAR100/senet/se_CIFAR100_4999.pt'