se_model:
  input_dims: 128
  hid_dims: [1024,1024]
  output_dims: 1024

dataset:
  path: "E:/dataset/feature/CIFAR100-MCR2"
  num: 2000

params: 
  batch_size: 200  
  learning_rate: 0.001
  epochs: 10000

device: 'cpu'