se_model:
  input_dims: 128
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 50000
  save_epoch: 5000
  eval_epoch: 10000

spec_model:
  input_dims: 128
  hid_dims: [1024,512]
  output_dims: 512
  num_cluster: 100
  epsilon: 0.001
  epochs: 10000
  save_epoch: 1000
  eval_epoch: 1000
  lambda: 10

dataset:
  path: "/root/dataset/CIFAR100-MCR2"
  num: 5000
  num_cluster: 100

params: 
  batch_size: 200  
  lr: 0.001

device: 'cuda'
reassign: 1