se_model:
  input_dims: 500
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 2000
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 200
  gamma: 200
  lmbd: 0.9

spec_model:
  input_dims: 500
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.001
  epochs: 2000
  save_epoch: 500
  eval_epoch: 100
  lr: 0.00007
  batch_size: 500
  lambda: 100
  alpha: 1

dataset:
  name: "FashionMNIST"
  path: "/root/dataset/FashionMNIST"
  num: 5000
  num_cluster: 10

params: 
  device: 'cuda'
  se_pretrained: True
  se_model_path: 'se_model/FashionMNIST/senet/se_FashionMNIST_1999.pt'