se_model:
  input_dims: 500
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 5000
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 200
  gamma: 200
  lmbd: 0.9

spec_model:
  input_dims: 500
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.001
  epochs: 2000
  save_epoch: 500
  eval_epoch: 100
  lr: 0.0007
  batch_size: 400
  lambda: 100

dataset:
  name: "MNIST"
  path: "/root/dataset/MNIST"
  num: 10000
  num_cluster: 10

params: 
  device: 'cuda'
  se_pretrained: True
  se_model_path: 'se_model/MNIST/senet/se_MNIST_2999.pt'