se_model:
  input_dims: 128
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 2500
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 200
  gamma: 200
  lmbd: 0.9

spec_model:
  input_dims: 128
  hid_dims: [1024,512]
  output_dims: 64
  epsilon: 0.0001
  epochs: 1600
  save_epoch: 200
  eval_epoch: 100
  lr: 0.00005
  batch_size: 500
  lambda: 100

dataset:
  name: "NUSWIDEOBJ"
  path: "/scalable_dsc/dataset/NUSWIDEOBJ"
  num: 8000
  num_cluster: 31

params: 
  device: 'cuda'
  se_pretrained: False
  se_model_path: 'se_model/NUSWIDEOBJ/NUSWIDEOBJ/se_NUSWIDEOBJ_2499_48.pt'