se_model:
  input_dims: 2000
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 2000
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 100

spec_model:
  input_dims: 2000
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.001
  epochs: 2000
  save_epoch: 500
  eval_epoch: 100
  lr: 0.00005
  batch_size: 200
  lambda: 100
  alpha: 1

dataset:
  name: "REUTERS"
  path: "/root/dataset/REUTERS10K-IDF"
  num: 2000
  num_cluster: 4

params: 
  device: 'cuda'
  se_pretrained: True
  se_model_path: 'se_model/REUTERS/senet/se_REUTERS_1999.pt'