se_model:
  input_dims: 2000
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 5000
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 400

spec_model:
  input_dims: 2000
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.001
  epochs: 2000
  save_epoch: 500
  eval_epoch: 100
  lr: 0.0003
  batch_size: 400
  lambda: 100

dataset:
  name: "REUTERS"
  path: "/root/dataset/REUTERS10K-IDF"
  num: 2000
  num_cluster: 4

params: 
  device: 'cuda'
  se_pretrained: False
  se_model_path: ''