se_model:
  input_dims: 128
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 5000
  save_epoch: 500
  eval_epoch: 10000
  lr: 0.001
  batch_size: 100
  gamma: 200
  lmbd: 0.9

spec_model:
  input_dims: 128
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.001
  epochs: 1500
  save_epoch: 300
  eval_epoch: 100
  lambda: 10
  lr: 0.00007
  batch_size: 200
  lambda: 100
  alpha: 1

dataset:
  name: "STL10"
  path: "/root/dataset/STL10-MCR2"
  num: 2000
  num_cluster: 10

params: 
  device: 'cuda'
  se_pretrained: True
  se_model_path: 'se_model/STL10/senet/se_STL10_1999.pt'