se_model:
  input_dims: 128
  hid_dims: [1024,1024]
  output_dims: 1024
  epochs: 5000
  save_epoch: 500
  eval_epoch: 10000

spec_model:
  input_dims: 128
  hid_dims: [1024,512]
  output_dims: 512
  epsilon: 0.001
  epochs: 2000
  save_epoch: 500
  eval_epoch: 100
  lambda: 10

dataset:
  name: "CIFAR100"
  path: "/root/dataset/CIFAR100-MCR2"
  num: 20000
  num_cluster: 100

params: 
  batch_size: 400  
  lr: 0.001

device: 'cuda'
reassign: 1